apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: poi-map-template
  title: Angular SPA for Points-of-Interest Map
  description: creates the angular spa for the workshop
  tags:
    - typescript
    - angular
    - workshop
spec:
  owner: rhdeveloper-workshop-authors
  type: service

  parameters:
    - title: Provide information about the GitLab location
      required:
        - gitlabGroup
      properties:
        gitlabGroup:
          title: Repo Owner
          type: string
          description: GitLab Organization
          default: {{ gitlab_group }}
          enum:
            - {{ gitlab_group }}
        description:
          title: Description
          type: string
          description: Help others understand what this component is for
          default: Angular SPA for Points-of-Interest Map
    - title: Provide information about the new component
      required:
        - namespace
        - owner
      properties:
        namespace:
          title: Namespace
          type: string
          description: Namespace
          default: poi
        owner:
          title: Owner
          type: string
          description: Owner of the component
          default: {{ gitlab_user }}
          enum:
            - {{ gitlab_user }}
    - title: Provide Build Information
      required:
        - image_host
        - image_tag
      properties:
        image_host:
          title: Image Host
          type: string
          description: Host for storing image (defaults to openshift internal)
          default: image-registry.openshift-image-registry.svc:5000
        image_tag:
          title: Image Tag
          default: latest
          type: string
          description: Image tag to use for storing in the internal registry
  steps:
    - id: templateSource
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          git_host: {{ gitlab_host }}
          gitlabGroup: {{ '${{parameters.gitlabGroup}}' }}
          repoName: {{ '${{parameters.namespace}}' }}-frontend
          owner: {{ '${{parameters.owner}}' }}
          cluster_id: {{ cluster_subdomain }}
          namespace: {{ '${{parameters.namespace}}' }}
          component_id: {{ '${{parameters.namespace}}' }}-poi-map-app
    - id: publishSource
      name: Publishing to Source Code Repository
      action: publish:gitlab
      input:
        sourcePath: ./source
        description: {{ '${{parameters.description}}' }}
        repoUrl: {{ gitlab_host }}?owner={{ '${{parameters.gitlabGroup}}' }}&repo={{ '${{parameters.namespace}}' }}-frontend
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: registerSource
      name: Registering the Source Code Component
      action: catalog:register
      input:
        repoContentsUrl: {{ '${{steps.publishSource.output.repoContentsUrl}}' }}
        catalogInfoPath: /catalog-info.yaml
    - id: templateGitops
      name: Generating the deployment resources and artefacts
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          git_host: {{ gitlab_host }}
          component_id: {{ '${{parameters.namespace}}' }}-poi-map-app
          description: {{ '${{parameters.description}}' }}
          destination: https://{{ gitlab_host }}/{{ '${{parameters.gitlabGroup}}' }}/{{ '${{parameters.namespace}}' }}-frontend-gitops.git
          source_repository: https://{{ gitlab_host }}/{{ '${{parameters.gitlabGroup}}' }}/{{ '${{parameters.namespace}}' }}-frontend.git
          repository_name: {{ '${{parameters.namespace}}' }}-frontend
          git_owner: {{ '${{parameters.gitlabGroup}}' }}
          cluster: {{ cluster_subdomain }}
          namespace: {{ '${{parameters.namespace}}' }}
          image_host: {{ '${{parameters.image_host}}' }}
          image_name: {{ '${{parameters.namespace}}' }}/poi-map-app
          image_tag: {{ '${{parameters.image_tag}}' }}
        targetPath: ./tenant-gitops
    - id: publishGitops
      name: Publishing to Deployment Resource Repository
      action: publish:gitlab
      input:
        repoUrl: {{ gitlab_host }}?owner={{ '${{parameters.gitlabGroup}}' }}&repo={{ '${{parameters.namespace}}' }}-frontend-gitops
        title: gitops resources for {{ '${{parameters.namespace}}' }}-poi-map-app
        description: gitops resources for {{ '${{parameters.namespace}}' }}-poi-map-app
        sourcePath: ./tenant-gitops
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: createArgoResources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: {{ '${{parameters.namespace}}' }}-poi-map-app-bootstrap
        argoInstance: main
        namespace: janus-argocd
        repoUrl: https://{{ gitlab_host }}/{{ '${{parameters.gitlabGroup}}' }}/{{ '${{parameters.namespace}}' }}-frontend-gitops.git
        path: 'argocd/'
  output:
    links:
      - title: Source Code Repository
        url: {{ '${{steps.publishSource.output.remoteUrl}}' }}
      - title: Pipeline status
        url: https://console-openshift-console{{ cluster_subdomain }}/dev-pipelines/ns/{{ '${{parameters.namespace}}' }}/
      - title: Open Component in catalog
        icon: catalog
        entityRef: {{ '${{steps.registerSource.output.entityRef}}' }}
